version: 2

project_name: lokan

builds:
  - id: lokan
    dir: ./engine
    main: ./cmd/lokan
    binary: lokan
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: lokan
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    files: []

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: avrebarra
    name: lokan
